name: aeguana
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  material_segmented_control: ^5.0.0
  grouped_list: ^5.1.2
  rxdart: ^0.27.7
  get_it: ^7.6.0
  persistent_bottom_nav_bar_v2: ^4.2.8
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/ui/assets/
  fonts:
    - family: Futura
      fonts:
      - asset: lib/ui/assets/futura/Futura-Bold-font.ttf
    - family: Futura-Md-BT
      fonts:
      - asset: lib/ui/assets/futura-md/FutuMd.ttf
    - family: Futura-Bd
      fonts:
      - asset: lib/ui/assets/futura-md/FutuBd.ttf